variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:latest

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .m2/repository

stages:
  - test

services:
  - postgres
variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  POSTGRES_HOST_AUTH_METHOD: trust

Test project:
  stage: test
  script:
    - mvn $MAVEN_OPTS -Dtest=TestTagResourceController test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml