image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

Build project:
  stage: build&test
  script:
    - mvn $MAVEN_OPTS compile

Test project:
  stage: build&test
  script:
    - mvn $MAVEN_OPTS test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml


