
image: maven:3.8.5-jdk-11

stages:
  - build&test
  - package
  - dockerise

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

services:
  - postgres

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

Test project:
  stage: build&test
  script:
    - mvn -Dtest="TestAuthenticationResourceController" $MAVEN_OPTS test
  artifacts:
    paths:
      - target/surefire-reports/TEST-*.xml
    reports:
      junit: target/surefire-reports/TEST-*.xml

Package project:
  stage: package
  script:
    - mvn -Dmaven.test.skip=true $MAVEN_OPTS package
  artifacts:
    paths:
      - target/*.jar
